###

GET https://project-vehicles.herokuapp.com/autos

###

GET https://project-vehicles.herokuapp.com/autos/1

###

POST https://project-vehicles.herokuapp.com/autos
Content-Type: application/json

{
  "id": 0,
  "model": "Mitsubishi",
  "vin": "IHSHK49LFDS309460",
  "regNumber": "m001it_116",
  "ownerId": 2
}

###

POST https://project-vehicles.herokuapp.com/autos
Content-Type: application/json

{
  "id": 3,
  "model": "Mazda",
  "vin": "AJHUE48QLID049838",
  "regNumber": "m002az_716",
  "ownerId": 5
}

###

DELETE https://project-vehicles.herokuapp.com/autos/7

###

GET https://project-vehicles.herokuapp.com/offenses

###

POST https://project-vehicles.herokuapp.com/media
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="mitsubishi.jpg"
Content-Type: image/jpeg

< ./mitsubishi.jpg
--WebAppBoundary--

###

POST https://project-vehicles.herokuapp.com/offenses
Content-Type: application/json

{
  "id": 0,
  "regNumber": "m001it_116",
  "article": "12.9.3",
  "amountFine": 1500,
  "urlPhoto": "",
  "paid": 0
}

###

GET https://project-vehicles.herokuapp.com/offenses/2

###

POST https://project-vehicles.herokuapp.com/offenses
Content-Type: application/json

{
  "id": 7,
  "regNumber": "e007ee_716",
  "article": "12.9.4",
  "amountFine": 2500,
  "urlPhoto": "/media/3dc5108d-602c-4493-a397-1776bf2aa353.jpeg",
  "paid": 1
}

###

GET https://project-vehicles.herokuapp.com/protocols

###

GET https://project-vehicles.herokuapp.com/protocols/b005mw_116?paid=false

###

GET https://project-vehicles.herokuapp.com/protocols/regNumberSumNoPaid?regNumber=b005mw_116

###

GET https://project-vehicles.herokuapp.com/protocols/Petrov

###

GET https://project-vehicles.herokuapp.com/protocols/nameSumNoPaid?name=Petrov

###